### ISSUE TITLE
Install issue on linux - LONG_BIT

### ISSUE THREAD

**Issue by bryandesser** [py4dstem/py4DSTEM#105]
I'm (unsuccessfully) trying to install py4DSTEM on a linux machine (Ubuntu 18.04.4 LTS). I've been having issues for some time, first using the previous set of install instructions, and now using the new instructions via `pip`. This works perfectly on my MacBook Pro; however, using the exact same commands I get the following error (full build output attached):

```
pyport.h:726:2: error: #error "LONG_BIT definition appears wrong for platfor#
       #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

```
I've tried completely wiping anaconda and starting fresh, but get the same result. It seems to build hyperspy and py4dstem just fine, but takes issue with traits...
[output.txt](https://github.com/py4dstem/py4DSTEM/files/4427278/output.txt)

```
Building wheels for collected packages: py4dstem, hyperspy, traits
  Building wheel for py4dstem (setup.py) ... done
  Created wheel for py4dstem: filename=py4DSTEM-0.8.0-py3-none-any.whl size=210894 sha256=e9d46f72fc040b2951647a08384f6b59e7ddf370e2d7845bfa89faac6f83ea1f
  Stored in directory: /tmp/pip-ephem-wheel-cache-_h3crypz/wheels/f7/28/99/3f5878b42aae41c5da53f79f24a3c0043f6149a21c83f61950
  Building wheel for hyperspy (setup.py) ... done
  Created wheel for hyperspy: filename=hyperspy-1.5.2-py3-none-any.whl size=27638949 sha256=0ff0b54d32483643bf47ae4515b0e0ed82b318df0fcbeea419f500bdc3077fb8
  Stored in directory: /tmp/pip-ephem-wheel-cache-_h3crypz/wheels/81/07/38/eca791ec3445e08d99a123ea208a1f20e429f824ab5abf3d79
  Building wheel for traits (setup.py) ... error
  Running setup.py clean for traits
Successfully built py4dstem hyperspy
Failed to build traits
Installing collected packages: traits, hyperspy, py4dstem
    Running setup.py install for traits ... error
```

Any suggestions would be greatly appreciated!

**Comment by iceaiai** [comment]
I have a similar issue but after install visual C++, the issue has been solved. However, if you install python 3.8 plus, you will have an error: module time has no attribute 'clock'.

**Comment by bsavitzky** [comment]
I believe this issue should now be resolved.  Apologies for the delay.  I've just uploaded a refactor to the python package index which removes a number of dependencies.  Installation of the current version (0.9.3) with pip was successful on my ubuntu 18.04.03 LTS machine.  Please try reinstalling!

**Comment by bryandesser** [comment]
(insert face palm here)

Thank you @bsavitzky for checking, but it may well have been my own doing: I had an old flag in $CFLAGS in my bash file that was definitely causing a problem. I removed it and everything compiled on Ubuntu 18.04.4 LTS.

**Comment by bsavitzky** [comment]
Cool, thanks! Closing issue.
