### ISSUE TITLE
module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by iceaiai** [py4dstem/py4DSTEM#106]
Dear all,
I have successfully installed the py4DSTEM but I found the python version is 3.8 plus. When I load py4DSTEM, error msg as the title came out. I guess this is python version issue. I am just wondering whether there will be another issues related to the newest python. Should I downgrade my python into earlier version?

**Comment by cmtowle** [comment]
I had this error too, and created a python 3.7 environment which fixed the problem.

**Comment by sezelt** [comment]
Can you post the full error? py4DSTEM does not use `time.clock` so this is coming from one of the dependencies, and I'm curious to know which one... It may be as simple as specifying the newest version for some other packages

**Comment by iceaiai** [comment]
@sezelt I have fixed this issue by replacing the time.clock with process_time(). I modified a file which counts the process time. But just cannot locate it anymore in my computer...
