### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by Olefin3** [py4dstem/py4DSTEM#111]
Hi All:
I tried to save a datacube after binning the data and used the command:
`filepath=r"C:\Users\51449\OneDrive\Documents\Berkeley Research\Obj R4_D4 2.h5"`
`save(0,filepath)`
"0" is the index of the dataobjects
 However, I get the following error:

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-16-024f7a976241> in <module>
      9 
     10 filepath=r"C:\Users\51449\OneDrive\Documents\Berkeley Research\Obj R4D4 1.h5"
---> 11 save(0,filepath)

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in save(data, outputfile, **kwargs)
    206         save_dataobject(data, outputfile, **kwargs)
    207     elif isinstance(data, int):
--> 208         save_dataobjects_by_indices([data], outputfile, **kwargs)
    209     elif isinstance(data, list):
    210         if all([isinstance(item,DataObject) for item in data]):

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in save_dataobjects_by_indices(index_list, outputfile, **kwargs)
    188     dataobject_list = [full_dataobject_list[i] for i in index_list]
    189 
--> 190     save_from_dataobject_list(dataobject_list, outputfile, **kwargs)
    191 
    192 #@log

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\log.py in logged_function(*args, **kwargs)
    106                                  datetime = localtime())
    107 
--> 108         return function(*args,**kwargs)
    109 
    110     return logged_function

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in save_from_dataobject_list(dataobject_list, outputfile, topgroup, overwrite, **kwargs)
     72     for metadata in metadata_list:
     73         group_metadata_current = group_metadata.create_group("metadata_{}".format(metadata._ind))
---> 74         save_metadata(metadata,group_metadata_current)
     75 
     76     ##### Data #####

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in save_metadata(metadata, group)
    458     if type(metadata.original_metadata.shortlist)==DictionaryTreeBrowser:
    459         transfer_metadata_tree_hs(metadata.original_metadata.shortlist,group_original_metadata_shortlist)
--> 460         transfer_metadata_tree_hs(metadata.original_metadata.all,group_original_metadata_all)
    461     else:
    462         transfer_metadata_tree_py4DSTEM(metadata.original_metadata.shortlist,group_original_metadata_shortlist)

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    490         if istree_hs(tree[key]):
    491             subgroup = group.create_group(key)
--> 492             transfer_metadata_tree_hs(tree[key],subgroup)
    493         else:
    494             if type(tree[key])==str:

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    490         if istree_hs(tree[key]):
    491             subgroup = group.create_group(key)
--> 492             transfer_metadata_tree_hs(tree[key],subgroup)
    493         else:
    494             if type(tree[key])==str:

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    490         if istree_hs(tree[key]):
    491             subgroup = group.create_group(key)
--> 492             transfer_metadata_tree_hs(tree[key],subgroup)
    493         else:
    494             if type(tree[key])==str:

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    490         if istree_hs(tree[key]):
    491             subgroup = group.create_group(key)
--> 492             transfer_metadata_tree_hs(tree[key],subgroup)
    493         else:
    494             if type(tree[key])==str:

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    490         if istree_hs(tree[key]):
    491             subgroup = group.create_group(key)
--> 492             transfer_metadata_tree_hs(tree[key],subgroup)
    493         else:
    494             if type(tree[key])==str:

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    490         if istree_hs(tree[key]):
    491             subgroup = group.create_group(key)
--> 492             transfer_metadata_tree_hs(tree[key],subgroup)
    493         else:
    494             if type(tree[key])==str:

c:\users\51449\downloads\py4dstem-dev\py4dstem-dev\py4DSTEM\file\io\write.py in transfer_metadata_tree_hs(tree, group)
    493         else:
    494             if type(tree[key])==str:
--> 495                 group.attrs.create(key,np.string_(tree[key]))
    496             else:
    497                 group.attrs.create(key,tree[key])

UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 0: ordinal not in range(128)

---------------------------------------------------------------------------

I searched on Google and found some anwsers here
https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20
but I don't know how to deal with it.
BTW, I have updated py4dstem to version 8

**Comment by sezelt** [comment]
Did you use the letter "&mu;" anywhere in your code or filenames?

How did you originally import the data and what detector is it from?

**Comment by Olefin3** [comment]
Thank you Steve,
The original import data name is:
"C:\Users\51449\OneDrive\Documents\Berkeley Research\TEAM 1 data\13_172x171_ss7nm_mono250_25.4ms_spot10_alpha0p5mrad_CL1p05m_c240um_LN2_300kV_bin2_halfframe_SI data (35)\Diffraction SI.dm4"
I imput through
`fp =  r"C:\Users\51449\OneDrive\Documents\Berkeley Research\TEAM 1 data\13_172x171_ss7nm_mono250_25.4ms_spot10_alpha0p5mrad_CL1p05m_c240um_LN2_300kV_bin2_halfframe_SI data (35)\Diffraction SI.dm4"`
`datacube = py4DSTEM.file.io.read(fp)`
The detector is Gatan K2 from TEAM 1

I am now trying to find the letter "μ"

**Comment by sezelt** [comment]
I think this is actually K3 data. The &mu; may be in the metadata. 

Can you send the full code that you used to reproduce the error as well? I want to see exactly what you ran.

**Comment by Olefin3** [comment]
Yes, this is K3 data from the session we did. I am sorry I typed the wrong number. 
I sent my codes to you through email

**Comment by sezelt** [comment]
Yes this seems to be caused by the K3 using Unicode in its metadata, which py4DSTEM doesn't like. 

A workaround for now would be to delete the metadata from your datacube:
```python
datacube.metadata = None
```
This will let you save the datacube and any results from it. (I would recommend that you actually don't save a new copy of the data. As long as you load it with the `'dmmmap`' option it is just as fast, and you don't need multiple copies.

I will look into a solution for this soon. It should be a small patch.
