### ISSUE TITLE
GUI unable to read .h5 format

### ISSUE THREAD

**Issue by cmtowle** [py4dstem/py4DSTEM#112]
GUI crashed when attempting to open an .h5 file as Gatan K2 data (counted data from the TEAM 0.5 4D camera, which is a K3, so that may be part of it). Using conda python 3.7.7.

CONSOLE DUMP
----------------------------------
```
"E:/4D STEM project/TEM images/25 March '20 TEAM 0.5/4D STEM/data_scan12_th3_electrons.h5"
Loading file E:/4D STEM project/TEM images/25 March '20 TEAM 0.5/4D STEM/data_scan12_th3_electrons.h5
E:/4D STEM project/TEM images/25 March '20 TEAM 0.5/4D STEM/data_scan12_th3_electrons.h5 is not a py4DSTEM file.
Reading Gatan binary files...
Traceback (most recent call last):
  File "c:\users\cmtow\anaconda3\envs\py4dstem\lib\site-packages\py4DSTEM\gui\viewer.py", line 306, in load_file
    self.datacube = read(fname, load='gatan_bin')
  File "c:\users\cmtow\anaconda3\envs\py4dstem\lib\site-packages\py4DSTEM\file\log.py", line 108, in logged_function
    return function(*args,**kwargs)
  File "c:\users\cmtow\anaconda3\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\read.py", line 100, in read
    output = read_gatan_binary(filename)
  File "c:\users\cmtow\anaconda3\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\read.py", line 222, in read_gatan_binary
    from . import gatanK2
  File "c:\users\cmtow\anaconda3\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\gatanK2.py", line 161
    assert axis in [(0,1), (2,3)], 'Only average DP and average image supported.'
                                                                                ^
TabError: inconsistent use of tabs and spaces in indentation
```

When importing the same file as 'Automatic' file type, I get the following pop-up error:
![image](https://user-images.githubusercontent.com/48322422/79731689-7c9c7880-82a7-11ea-9513-2bc8918f9b5e.png)

**Comment by sezelt** [comment]
4D Camera data is currently not supported by the GUI. 

You can convert it to a standard DataCube, bin it, and save to a supported EMD file with something like this:
```python
import py4DSTEM
counted_dc = py4DSTEM.file.io.read('/path/to/data',load='kitware_counted_mmap')
dc = counted_dc.densify(bin_r=2,bin_Q=4)
py4DSTEM.file.io.save(dc,'/path/to/save/densified/data')
```
Keep in mind that the file size can become quite large if you don't bin because you lose the high compression of counted data!

The attached notebook has some details of how to work with electron counted data from the 4D camera:
[EMD CountedDatacube example.ipynb.zip](https://github.com/py4dstem/py4DSTEM/files/4502217/EMD.CountedDatacube.example.ipynb.zip)

**Comment by ercius** [comment]
@sezelt Im trying to add support to output the counted data from Kitware's stempy software directly to a py4dstem compatible dataset. Is there an option in `py4dstem.file.io.read()` to read a [counted dataset](https://emdatasets.com/format/) (counted_datacubes group) from a EMD v0.7 format H5 file? The function doesnt look like it supports counted data sets.

**Comment by sezelt** [comment]
Hey Peter,
Reading of py4DSTEM EMD files is all handled in the `FileBrowser`. Here is the section for `CountedDataCube`: 
https://github.com/py4dstem/py4DSTEM/blob/4caff085d2a6227394dba3fe1e1c16edf8f0ea46/py4DSTEM/file/io/filebrowser.py#L819-L841
Writing them is handled here:
https://github.com/py4dstem/py4DSTEM/blob/4caff085d2a6227394dba3fe1e1c16edf8f0ea46/py4DSTEM/file/io/write.py#L271-L329
