### ISSUE TITLE
Which functions are supported for polar transforms of data

### ISSUE THREAD

**Issue by tcpekin** [py4dstem/py4DSTEM#114]
Hi @bsavitzky, I want to polar transform my stack, but I'm unsure if I should use the [`cartesian_to_polarelliptical_transform.py`](https://github.com/py4dstem/py4DSTEM/blob/4caff085d2a6227394dba3fe1e1c16edf8f0ea46/py4DSTEM/process/utils/cartesian_to_polarelliptical_transform.py#L11) code or the functions found in [`ellipticalCoords.py`](https://github.com/py4dstem/py4DSTEM/blob/4caff085d2a6227394dba3fe1e1c16edf8f0ea46/py4DSTEM/process/utils/ellipticalCoords.py#L21). I think both need to be updated to work with the new ellipse fitting functions now as well, since A is no longer a free parameter, and instead we have a radius value, and I would rather fix the one that will be kept going forward, versus some legacy code. Also, I'm not sure 100% that they need to be updated yet. If they have been already please let me know.

Thanks,
Tom

**Comment by bsavitzky** [comment]
Yup, this needs to be cleaned up to remove the older functions.  Use
cartesianDataAr_to_polarEllipticalDataAr, found in ellipticalCoords.py.

**Comment by tcpekin** [comment]
Awesome, thanks for the quick response.

**Comment by alex-rakowski** [comment]
Looks like `cartesian_to_polarelliptical_transform.py` has been removed, assume this closeable?
