### ISSUE TITLE
Package importing: scikit 0.17.2 incompatible with hyperspy

### ISSUE THREAD

**Issue by lerandc** [py4dstem/py4DSTEM#115]
Current versions of hyperspy (v1.5.2) imports scikit.features.register_translation, which has been deprecated as of May 8th with scikit v0.17.2. Leads to an import error stemming from py4DSTEM/file/datastructure/metadata.py

Looks like their next release will address this: https://github.com/hyperspy/hyperspy/pull/2393

**Comment by Olefin3** [comment]
I also had this error 
`  File "c:\users\ickao\anaconda2\envs\py4dstem\lib\site-packages\hyperspy\_signals\signal2d.py", line 26, in <module>
    from skimage.feature.register_translation import _upsampled_dft`
`ModuleNotFoundError: No module named 'skimage.feature.register_translation'`
I tried to search this problem and find this

> skimage.feature.register_translation(src_image, target_image, upsample_factor=1, space='real', return_error=True)[source]

> Deprecated function. Use skimage.registration.phase_cross_correlation instead

**Comment by Olefin3** [comment]
Is there any one 

> Current versions of hyperspy (v1.5.2) imports scikit.features.register_translation, which has been deprecated as of May 8th with scikit v0.17.2. Leads to an import error stemming from py4DSTEM/file/datastructure/metadata.py
> 
> Looks like their next release will address this: [hyperspy/hyperspy#2393](https://github.com/hyperspy/hyperspy/pull/2393)

I wonder whether you have already fixed this problem? Thank you.

**Comment by bsavitzky** [comment]
Hey @lerandc, @Olefin3 - I'm working on this now. I think I should have it fixed and merged here sometime tomorrow.  Will post again and close the ticket when it's done.

**Comment by bsavitzky** [comment]
This issue is fixed - please try reinstalling with pip.  Sorry for the long delay.
