### ISSUE TITLE
No module named 'py4DSTEM.file.io.native.filebrowser'

### ISSUE THREAD

**Issue by DanielleM1** [py4dstem/py4DSTEM#117]
I get ModuleNotFoundError: No module named 'py4DSTEM.file.io.native.filebrowser' when trying to run the package. Looks like file/io/native/copy.py references filebrowser, but filebrowser is not in the directory.

**Comment by bsavitzky** [comment]
This issue should now be resolved with a new update in the python package index.  Try reinstalling.  If you followed the normal installation instructions, you can run from a terminal

```
conda activate py4dstem
pip uninstall py4DSTEM
pip install py4DSTEM
```

**Comment by bryandesser** [comment]
I get a similar issue with an install/compilation from this morning of the latest version:

`File "~/anaconda3/envs/py4dstem/lib/python3.8/site-packages/py4DSTEM/gui/utils.py", line 14, in <module>`
`    from ..file.io.filebrowser import FileBrowser`
`ModuleNotFoundError: No module named 'py4DSTEM.file.io.filebrowser'`

I did a complete removal of py4dstem and the conda environment and started from scratch.

**Comment by bsavitzky** [comment]
My previous update jumped the gun on this issue being fully resolved - but now it should be good to go.  Please try pip installing again - the latest version now is 0.9.5, which shoooould take care of the FileBrowser bug once and for all.  Thanks for your patience!

**Comment by Tsdarmstadt** [comment]
Dear bsavitzky,

I still got (_AttributeError: module 'py4DSTEM.file.io' has no attribute 'FileBrowser'_) when running the _py4dstem 0.9.6._ Is this erro fixed?

> My previous update jumped the gun on this issue being fully resolved - but now it should be good to go. Please try pip installing again - the latest version now is 0.9.5, which shoooould take care of the FileBrowser bug once and for all. Thanks for your patience!

**Comment by bsavitzky** [comment]
Hmm, that's odd, this error should be fully resolved.  Can you send the
full error message?

**Comment by Tsdarmstadt** [comment]
Dear bsavitzky,
thank you very much for your reply.
Please find the full erro message attached here.
[image: image.png]
Best regards,
Tianshu

bsavitzky <notifications@github.com> 于2020年6月23日周二 下午7:31写道：

**Comment by Tsdarmstadt** [comment]
Dear bsavitzky,
thank you very much for your reply.
Please find the full erro message attached here.
`Traceback (most recent call last):
  File "New-folder\read.py", line 17, in <module>
    fb = py4DSTEM.file.io.FileBrowser(args.filename)
AttributeError: module 'py4DSTEM.file.io' has no attribute 'FileBrowser' `
Best regards,
Tianshu

**Comment by bsavitzky** [comment]
It looks like you're running a file that was written for an older version of the package - your file is trying to load the FileBrowser class, which doesn't exist anymore.  You'll have to update your file.  The new read syntax for native files is
```
py4DSTEM.file.io.read(fp)
```
to print the contents of a py4DSTEM formatted h5 file located at `fp`, and 
```
data,_ = py4DSTEM.file.io.read(fp, data_id=X)
```
to load data, where X is an identifier that can either be a string (the name of the data you want) or an integer (the index of the data you want).  Both names and indices are printed by the previous command.

**Comment by Tsdarmstadt** [comment]
Dear bsavitzky,

thank you very much for your help. I am quite new in using py4DSTEM.
The output file still could not be loaded. This output was created in 3D by using _Prismatic_.

`KeyError                                  Traceback (most recent call last)
<ipython-input-15-4f1aae8d15af> in <module>
----> 1 fb=py4DSTEM.file.io.read(hdffile)

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\read.py in read(fp, mem, binfactor, ft, **kwargs)
     70 
     71     if ft == "py4DSTEM":
---> 72         data,md = read_py4DSTEM(fp, mem=mem, binfactor=binfactor, **kwargs)
     73     elif ft == "dm":
     74         data,md = read_dm(fp, mem, binfactor, **kwargs)

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\native\read_py4DSTEM.py in read_py4DSTEM(fp, **kwargs)
     54     """
     55     assert(is_py4DSTEM_file(fp)), "Error: {} isn't recognized as a py4DSTEM file.".format(fp)
---> 56     version = get_py4DSTEM_version(fp)
     57     if not version_is_geq(version,(0,9,0)):
     58         return read_py4DSTEM_legacy(fp, **kwargs)

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\native\read_utils.py in get_py4DSTEM_version(fp, topgroup)
     32     assert(is_py4DSTEM_file(fp)), "Error: not recognized as a py4DSTEM file"
     33     with h5py.File(fp,'r') as f:
---> 34         version_major = int(f[topgroup].attrs['version_major'])
     35         version_minor = int(f[topgroup].attrs['version_minor'])
     36         if 'version_release' in f[topgroup].attrs.keys():

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\h5py\_hl\group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object '4DSTEM_experiment' doesn't exist)"
`
May I ask if you have any idea about that?

BR,

**Comment by Tsdarmstadt** [comment]
Dear @bsavitzky ,

as far as I understand, my hdf5-file was loaded through funciton `read_py4DSTEM(fp, **kwargs)`, but it failed. May I ask if you have idea on this? Is the reason that the format of my hdf5-file is not compatible with py4DSTEM?

Thank you very much for you time.
BR,
```
KeyError                                  Traceback (most recent call last)
<ipython-input-7-ade85297ac96> in <module>
----> 1 fb = py4DSTEM.file.io.read("C:\\Users\\user1\\Desktop\\lecture\\New-folder\\SMO50-50.h5")

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\read.py in read(fp, mem, binfactor, ft, **kwargs)
     70 
     71     if ft == "py4DSTEM":
---> 72         data,md = read_py4DSTEM(fp, mem=mem, binfactor=binfactor, **kwargs)
     73     elif ft == "dm":
     74         data,md = read_dm(fp, mem, binfactor, **kwargs)

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\native\read_py4DSTEM.py in read_py4DSTEM(fp, **kwargs)
     54     """
     55     assert(is_py4DSTEM_file(fp)), "Error: {} isn't recognized as a py4DSTEM file.".format(fp)
---> 56     version = get_py4DSTEM_version(fp)
     57     if not version_is_geq(version,(0,9,0)):
     58         return read_py4DSTEM_legacy(fp, **kwargs)

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\py4DSTEM\file\io\native\read_utils.py in get_py4DSTEM_version(fp, topgroup)
     32     assert(is_py4DSTEM_file(fp)), "Error: not recognized as a py4DSTEM file"
     33     with h5py.File(fp,'r') as f:
---> 34         version_major = int(f[topgroup].attrs['version_major'])
     35         version_minor = int(f[topgroup].attrs['version_minor'])
     36         if 'version_release' in f[topgroup].attrs.keys():

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

C:\Tianshu\Software\anaconda\envs\py4dstem\lib\site-packages\h5py\_hl\group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object '4DSTEM_experiment' doesn't exist)"
```

**Comment by bsavitzky** [comment]
Hey @Tsdarmstadt,

It looks like that's probably the case.  Was this a file written with
py4DSTEM, or is it some other HDF5 file?  Currently the read functions only
support H5 files written by py4DSTEM.  For other HDF5 files, you can use
the h5py package to read the data manually.

**Comment by Tsdarmstadt** [comment]
Hello @bsavitzky ,

It is some other HDF5 file. I am now using the h5py package. Thank you very much for your suggestions.
Would it be possible in future that other HDF5 files could be read by py4dstem?

Best regards,

**Comment by bsavitzky** [comment]
HDF5 files are a very general file format, designed to be very flexible to
fill many different kinds of use cases. So in general, there isn't really
any way to support reading "general" HDF5 files. On the other hand, many
more specific file formats are built on HDF5 - including the py4DSTEM
format - so if there are other specific H5 filetypes if interest, it could
be possible to support them.
