### ISSUE TITLE
alpha transparency not implemented in show_points

### ISSUE THREAD

**Issue by BenMiller002** [py4dstem/py4DSTEM#127]
the py4DSTEM.visualize.show_points function in visualize.py has an input value **alpha** to set the transparency of the points, but this input value is not used. It would be nice to have transparency for the points, so they don't block the underlying diffraction pattern spots.  
```
def show_points(ar,x,y,s=1,scale=500,alpha=1,point_color='r',
                min=0,max=3,power=1,figsize=(12,12),returnfig=False,**kwargs):
```

**Comment by bsavitzky** [comment]
This is fixed in my testing.  If you have/find a use-case where it still fails, please re-open the issue!  Very sorry for the long delay...
