### ISSUE TITLE
h5 files are not presently supported.

### ISSUE THREAD

**Issue by Chuqiao2333** [py4dstem/py4DSTEM#130]
In the classification_twinBoundary.ipynb file, the sample input is a h5 file, but it can not be read from :

py4DSTEM.io.read(filepath_input)

**Comment by bsavitzky** [comment]
This reads correctly on my system and on the other computers we've tested on.  Can you add some additional information or show an error message?  To confirm, are you are using the sample .h5 file linked in that notebook, as per the instructions in the first cell of the notebook?

**Comment by Chuqiao2333** [comment]
Thank you for your reply. Here is the error message.

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-53035f625668> in <module>
      1 # Examine what's inside the data file
----> 2 py4DSTEM.io.read(filepath_input)

/opt/anaconda3/envs/py4dstem/lib/python3.8/site-packages/py4DSTEM/io/read.py in read(fp, mem, binfactor, ft, metadata, **kwargs)
     88 
     89     if ft is None:
---> 90         ft = parse_filetype(fp)
     91 
     92     if ft == "py4DSTEM":

/opt/anaconda3/envs/py4dstem/lib/python3.8/site-packages/py4DSTEM/io/read.py in parse_filetype(fp)
    118             return 'py4DSTEM'
    119         else:
--> 120             raise Exception("Non-py4DSTEM formatted .h5 files are not presently supported.")
    121     elif fext in ['.dm','.dm3','.dm4','.DM','.DM3','.DM4']:
    122         return 'dm'

Exception: Non-py4DSTEM formatted .h5 files are not presently supported.

It seems the io.read can only read .dm files instead of .h5 files?

**Comment by bsavitzky** [comment]
It looks like `filepath_input` has not been changed.  If you read the opening cell of this notebook, under "Data", it describes how you'll need to download the sample data to your own computer, then *update the variable `filepath_input` to reflect that path to the file*.  That means you need to change this variable to reflect wherever you've put this file on your computer.

Based on what I can see here, my best guess at this point is that you're asking py4DSTEM to load a file that doesn't exist on your computer (i.e. there's no file at that path).  There should be an error message to reflect this - I'll add this when I get a chance, thanks for catching this need.

I'm not certain why you're thinking that only .dm files are read - this is not the case.  However one last note is that the code reads .h5 files *in the py4DSTEM format*.  It does not read generic .h5 file.

**Comment by Chuqiao2333** [comment]
![image](https://user-images.githubusercontent.com/53119502/95141689-6c6c4d00-07a4-11eb-8e90-daab04e5f73e.png)
I did downloaded the files. Sorry I didn't show that.

I just realize the problems. It is that I didn't completely download the .h5 file. The download just stopped and I didn't realize it. But anyway I can run it normally now. Thank you so much for you reply patiently

**Comment by bsavitzky** [comment]
Glad its working for you now! 👍
