### ISSUE TITLE
I can't find the "Browse" button in the main window, and when I change the size of whole window, I still can't get this button.

### ISSUE THREAD

**Issue by yabowang-deeper** [py4dstem/py4DSTEM#133]

**Comment by alex-rakowski** [comment]
Assume you are referring to the GUI? If so there are known issues with it, we are working on.  We will post and update here https://github.com/py4dstem/py4DSTEM#running-the-gui when the GUI is functional again

**Comment by bsavitzky** [comment]
@sezelt is this fixed in the current GUI?

**Comment by sezelt** [comment]
yes
