### ISSUE TITLE
Reporting incompatibility with python3.6 and ncempy 1.8.0

### ISSUE THREAD

**Issue by ercius** [py4dstem/py4DSTEM#135]
@w4m0330 reported an incompatibility between ncempy (a dependency of py4dstem) and python 3.6. A fix has been implemented in ercius/openNCEM#29. The current workaround is to use python 3.7 or 3.8. 

A fix has been implemented in ercius/openNCEM#30 and will be distributed in ncempy 1.8.1 on pypi soon.

Updating the ncempy version in py4dstem's setup.py would avoid this in the future.

**Comment by bsavitzky** [comment]
py4DSTEM version 0.11.6+ uses ncempy 1.8.1.  Thanks Peter.
