### ISSUE TITLE
TKTK

### ISSUE THREAD

**Issue by Xiaoyue-Gao** [py4dstem/py4DSTEM#137]
i dont know what is the TKTK in Annotation,pls help!

**Comment by alex-rakowski** [comment]
Could you prove a little more information, Where did you see `TKTK`? Was it an error message?  If so what code were you trying to execute? 

The only references  `TK` I could find are comments in  `py4DSTEM/io/read.py` and in `py4DSTEM/io/native/README.txt` . If so they won't affect the code, and I suspect they are simply tags/reminders for @bsavitzky while he was writing the code.

**Comment by Xiaoyue-Gao** [comment]
I think it is just the bsavitzky's personal writing habits~
