### ISSUE TITLE
Probe template construction often fails due to reliance on Center of Mass function

### ISSUE THREAD

**Issue by cophus** [py4dstem/py4DSTEM#149]
Using 
`xCoM, yCoM = py4DSTEM.process.diskdetection.get_CoM(image_probe_mean)`
to build a probe template is very prone to failure.  The other py4DSTEM function:
`r,qx0,qy0 = py4DSTEM.process.calibration.get_probe_size(image_probe_mean)`
is significantly more reliable.  Below you can see a screenshot of a pretty typical dataset where CoM fails, with the image also attached in numpy format.  

These functions should be updated with the more robust function:
**py4DSTEM.process.diskdetection.get_probe_kernel

py4DSTEM.process.diskdetection.get_probe_kernel_subtrgaussian
py4DSTEM.process.diskdetection.get_probe_kernel_logistictrench**

![image](https://user-images.githubusercontent.com/796309/118379093-11e26d00-b58d-11eb-9baf-4021a62487a4.png)
[mean_probe_image.zip](https://github.com/py4dstem/py4DSTEM/files/6488324/mean_probe_image.zip)

**Comment by bsavitzky** [comment]
This issue is solved by PR #152
