### ISSUE TITLE
Misleading reader errors

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#151]
If you point `py4DSTEM.io.read(fpath)` to an invalid filepath, the error (below) that gets raised will say that the file is not a valid py4DSTEM EMD file. A check should be performed to check the filepath exists and warn the user in case it does not.

```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-3-ed6e5a87f2fd> in <module>
----> 1 py4DSTEM.io.read(filepath)

~/anaconda3/envs/py4d-latest/lib/python3.9/site-packages/py4DSTEM/io/read.py in read(fp, mem, binfactor, ft, metadata, **kwargs)
     88 
     89     if ft is None:
---> 90         ft = parse_filetype(fp)
     91 
     92     if ft == "py4DSTEM":

~/anaconda3/envs/py4d-latest/lib/python3.9/site-packages/py4DSTEM/io/read.py in parse_filetype(fp)
    118             return 'py4DSTEM'
    119         else:
--> 120             raise Exception("Non-py4DSTEM formatted .h5 files are not presently supported.")
    121     elif fext in ['.dm','.dm3','.dm4','.DM','.DM3','.DM4']:
    122         return 'dm'

Exception: Non-py4DSTEM formatted .h5 files are not presently supported.
```

**Comment by bsavitzky** [comment]
Hey Steve - which version of py4DSTEM are you using?  This problem should already be solved in the latest version of the code.......

**Comment by sezelt** [comment]
Aha yes it seems I did not have the latest version.

(I thought I did have the latest, since I did a fresh install, but for some odd reason `pip` decided to install v0.11.x. This seems to be because of some lingering numpy + python 3.9 weirdness. But we are currently officially telling people to use 3.7, so that's whatever.)
