### ISSUE TITLE
py4DSTEM GUI issue

### ISSUE THREAD

**Issue by PhysXu** [py4dstem/py4DSTEM#156]
I followed the instruction in Github for installing py4DSTEM:

          conda update conda
          conda create -n py4dstem python==3.7
          conda activate py4dstem
          conda install pip
          pip install py4dstem
          conda install pywin32

But when I try to run the GUI by

          conda activate py4dstem
          py4dstem

It tells me:
![image](https://user-images.githubusercontent.com/35793078/120061920-09f8f180-c092-11eb-8f9d-4647e79f9a20.png)

**Comment by alex-rakowski** [comment]
The GUI is currently broken, and we are working on the fix. We'll post an update here https://github.com/py4dstem/py4DSTEM#running-the-gui , when it is fixed.
