### ISSUE TITLE
AttributeError: module 'py4DSTEM.io.datastructure' has no attribute 'Coordinates'

### ISSUE THREAD

**Issue by AutoEM** [py4dstem/py4DSTEM#158]
I can read the example  "./calibrationData_simulatedAuNanoplatelet_binned.h5" file but it gives then an error:
any ideas?

thx

import numpy as np
import matplotlib.pyplot as plt
import py4DSTEM
from os import path
.
filepath = "./calibrationData_simulatedAuNanoplatelet_binned.h5"
py4DSTEM.io.read(filepath)
Index     Type              Shape                   Name                                                  
-----     ----              -----                   ----                                                  
  0       DataCube          (100, 84, 125, 125)     polyAu_4DSTEM                                         
  1       DataCube          (100, 84, 125, 125)     simulation_4DSTEM                                     
  2       DiffractionSlice  (512, 512)              defocused_probe                                       
  3       DiffractionSlice  (125, 125)              probe_template                                        
datacube_cal = py4DSTEM.io.read(filepath,data_id='polyAu_4DSTEM')
probe_template = py4DSTEM.io.read(filepath,data_id='probe_template').data
defocused_probe = py4DSTEM.io.read(filepath,data_id='defocused_probe').data
datacube_rotation = py4DSTEM.io.read(filepath,data_id='simulation_4DSTEM')
coordinates = py4DSTEM.io.datastructure.Coordinates(datacube_cal.R_Nx,datacube_cal.R_Ny,
                                                   datacube_cal.Q_Nx,datacube_cal.Q_Nx,
                                                   name='coordinates_calibrationdata')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-601a6cafa6b4> in <module>
----> 1 coordinates = py4DSTEM.io.datastructure.Coordinates(datacube_cal.R_Nx,datacube_cal.R_Ny,
      2                                                    datacube_cal.Q_Nx,datacube_cal.Q_Nx,
      3                                                    name='coordinates_calibrationdata')

AttributeError: module 'py4DSTEM.io.datastructure' has no attribute 'Coordinates'

**Comment by alex-rakowski** [comment]
Not 100% about the dataset you are referring to, but I think you need to upgrade your py4DSTEM package. Try running `pip install py4dstem -U`
