### ISSUE TITLE
AttributeError: 'Coordinates' object has no attribute 'get_center'

### ISSUE THREAD

**Issue by sqshao0506** [py4dstem/py4DSTEM#159]
Hi, I meet an issue in the Calibration script showing below:

# Center the disk positions about the origin
braggpeaks_centered = py4DSTEM.process.calibration.center_braggpeaks(braggpeaks_raw,coords=coordinates)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-8e317c7ffd51> in <module>
      1 # Center the disk positions about the origin
----> 2 braggpeaks_centered = py4DSTEM.process.calibration.center_braggpeaks(braggpeaks_raw,coords=coordinates)

~\AppData\Roaming\Python\Python38\site-packages\py4DSTEM\process\calibration\origin.py in center_braggpeaks(braggpeaks, qx0, qy0, coords, name)
    379                                 "Either (qx0,qy0) or coords must be specified")
    380     if coords is not None:
--> 381         qx0,qy0 = coords.get_center()
    382         assert qx0 is not None and qy0 is not None, "coords did not contain center position"
    383     if name is None:

AttributeError: 'Coordinates' object has no attribute 'get_center'

Anyone has an idea? Thanks in advance.

**Comment by alondoc** [comment]
This was fixed in the newer code. 
Change in the file origin.py (on py4DSTEM\process\calibration\origin.py) line 381 in your version

qx0,qy0 = coords.get_center()

for

 qx0,qy0 = coords.get_origin()

**Comment by sqshao0506** [comment]
Hi alondoc, brilliant thanks!
