### ISSUE TITLE
AssertionError in Strainmap.ipynb

### ISSUE THREAD

**Issue by sqshao0506** [py4dstem/py4DSTEM#160]
Hi, 
When I executed strainmap_crystalline-Strainmap.ipynb in the sample code, there is a issue of AssertionError showing below:

_Fit reciprocal lattice vectors at each scan position_
g1g2_map = py4DSTEM.process.latticevectors.fit_lattice_vectors_all_DPs(braggpeaks_indexed, minNumPeaks=6)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-33-8df1278408c5> in <module>
      1 # Fit reciprocal lattice vectors at each scan position
----> 2 g1g2_map = py4DSTEM.process.latticevectors.fit_lattice_vectors_all_DPs(braggpeaks_indexed, minNumPeaks=6)

C:\ProgramData\Anaconda3\lib\site-packages\py4DSTEM\process\latticevectors\fit.py in fit_lattice_vectors_all_DPs(braggpeaks, x0, y0, minNumPeaks)
     94     """
     95     assert isinstance(braggpeaks, PointListArray)
---> 96     assert np.all([name in braggpeaks.dtype.names for name in ('qx','qy','intensity','h','k','index_mask')])
     97 
     98     # Make RealSlice to contain outputs

AssertionError: 
---------------------------------------------------------------------------

I am trying to overcome it with looking at the source code.
Any ideas? Thanks in advance!

**Comment by alex-rakowski** [comment]
We're in the process of moving sample tutorials over to a new repo, https://github.com/py4dstem/py4DSTEM_tutorials. I'd suggest looking at those ones as they will definitely run. The examples in this repo need updating to avoid errors like these.

**Comment by sqshao0506** [comment]
Hi Alex,

Thanks for your reply.
