### ISSUE TITLE
AttributeError in "show with calibration.ipynb"

### ISSUE THREAD

**Issue by sqshao0506** [py4dstem/py4DSTEM#161]
Hi 
There is an issue in Sample code - Visualize - "show with calibration.ipynb" showing below:

vis.show(dp_max,scaling='log',figsize=(6,6),scalebar={},
         coordinates=coordinates)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\py4DSTEM\visualize\show.py in show(ar, figsize, cmap, scaling, clipvals, min, max, power, bordercolor, borderwidth, returnclipvals, returncax, returnfig, figax, hist, n_bins, mask, mask_color, rectangle, circle, annulus, ellipse, points, grid_overlay, cartesian_grid, polarelliptical_grid, rtheta_grid, scalebar, coordinates, rx, ry, space, pixelsize, pixelunits, x0, y0, e, theta, **kwargs)
    268             try:
--> 269                 x0 = coordinates.get_qx0(rx,ry)
    270             except AttributeError:

C:\ProgramData\Anaconda3\lib\site-packages\py4DSTEM\io\datastructure\coordinates.py in get_qx0(self, rx, ry)
    138     def get_qx0(self,rx=None,ry=None):
--> 139         return self._get_value(self.qx0,rx,ry)
    140     def get_qy0(self,rx=None,ry=None):

AttributeError: 'Coordinates' object has no attribute 'qx0'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-9-201bc62808a1> in <module>
----> 1 vis.show(dp_max,scaling='log',figsize=(6,6),scalebar={},
      2          coordinates=coordinates)

C:\ProgramData\Anaconda3\lib\site-packages\py4DSTEM\visualize\show.py in show(ar, figsize, cmap, scaling, clipvals, min, max, power, bordercolor, borderwidth, returnclipvals, returncax, returnfig, figax, hist, n_bins, mask, mask_color, rectangle, circle, annulus, ellipse, points, grid_overlay, cartesian_grid, polarelliptical_grid, rtheta_grid, scalebar, coordinates, rx, ry, space, pixelsize, pixelunits, x0, y0, e, theta, **kwargs)
    269                 x0 = coordinates.get_qx0(rx,ry)
    270             except AttributeError:
--> 271                 raise Exception('The Coordinates instance passed does not contain a value for qx0')
    272         else:
    273             x0 = 0

Exception: The Coordinates instance passed does not contain a value for qx0
---------------------------------------------------------------------------

Any ideas? Thanks in advance.

**Comment by alex-rakowski** [comment]
We are moving the tutorials/sample code over to a new repo, https://github.com/py4dstem/py4DSTEM_tutorials. Check these out as they all run. The notebooks in this repo need updating to avoid errors like these.
