### ISSUE TITLE
Combining x and y arguments into a single argument

### ISSUE THREAD

**Issue by cophus** [py4dstem/py4DSTEM#170]
py4DSTEM functions currently often pass in both 'x' and 'y' as separate arguments, or 'q_x' and 'q_y' separately.  There is no good reason for this - when working with image data, you will never find one without the other.  We should therefore combine these arguments whenever possible.  

For example, a diffraction space input argument for the center position might currently be:
...  , qx0, qy0, ....
which could become
... , qxy_origin_pixels, ...
or perhaps just
... , qxy_origin, ...

This would be a 2 element numpy vector:
qxy_origin[0] = qx0
qxy_origin[1] = qy0

**Comment by bsavitzky** [comment]
Agreed - this has been updated in many places, and I think this is established best-practice moving forward now.  I think we can close the issue for now, what do you think @cophus ?
