### ISSUE TITLE
Bragg vector maps have an incorrect center pixel

### ISSUE THREAD

**Issue by cophus** [py4dstem/py4DSTEM#172]
See the below example image:

![image](https://user-images.githubusercontent.com/796309/122978106-f9fbc700-d34a-11eb-854e-43b2ca4162dc.png)

The "center coordinate" of an FFT-shifted image with dimensions [Nx Ny] should be [Nx Ny]/2 in python indexing.  However, it is currently set to ( [Nx Ny] -1) /2 or ( [Nx Ny] +1) /2.  This leads to the center coordinate being spread over a 2x2 pixel group, rather than a single pixel.

**Comment by cophus** [comment]
This image was generated by these command lines:

bragg_vector_map = py4DSTEM.process.diskdetection.get_bvm(
    bragg_peaks_centered,
    dataset.Q_Nx,
    dataset.Q_Ny)

# plot the Bragg vector map
py4DSTEM.visualize.show(
    bragg_vector_map,
    cmap='inferno',
    clipvals='manual',
    min=0,
    max=1e4)

**Comment by bsavitzky** [comment]
Hey Colin - I certainly agree that the center spot is spread over 4 pixels here.  However I'm not sure your assessment of what's wrong is quite right.  The relevant function does:

```
    braggvectormap = np.zeros((Q_Nx,Q_Ny))
    qx0,qy0 = Q_Nx/2.,Q_Ny/2.
    for (Rx, Ry) in tqdmnd(braggpeaks.shape[0],braggpeaks.shape[1],
                           desc='Computing Bragg vector map',unit='DP',unit_scale=True):
        peaks = braggpeaks.get_pointlist(Rx,Ry)
        for i in range(peaks.length):
            qx = peaks.data['qx'][i]+qx0
            qy = peaks.data['qy'][i]+qy0
            I = peaks.data['intensity'][i]
            braggvectormap = add_to_2D_array_from_floats(braggvectormap,qx,qy,I)
    return braggvectormap
```

(see process/diskdetection/braggvectormap.py, line 22)

The center point is being set to (Q_Nx/2,Q_Ny/2).  Similarly, the disk centering function (see process/calibration/origin.py) looks correct to me.  So I'm not sure what's going on here!

**Comment by bsavitzky** [comment]
In v14.0 we no longer put the center pixel at the array center in BVMs - instead, the center is just the mean center position from the diffraction data.  Closing this issue - if I've missed something, please re-open it.
