### ISSUE TITLE
Question: parallel (multicore) processing?

### ISSUE THREAD

**Issue by miaoleixin1994** [py4dstem/py4DSTEM#178]
Dear Developers,

I hope you are doing well! I really appreciate your effort in creating this wonderful package. I enjoy using the package a lot, and I just have one question: is there a way to utilize the parallel processing capability of the CPUs in this package? I noticed for most of the processing, the code seems to only use a single thread. 

I am a little new to python coding so I am still figuring out how to use the parallel mode. I would appreciate it if you can help me with this because using parallel processing can accelerate the processing a lot. For one of my datasets, its dimension is 1024*1024*100*200, and the calibration alone can take over one hour to finish. If multithread can be used, I guess the time can be cut at least by half. 

Thank you again for your effort and your help!

**Comment by cophus** [comment]
Hi @miaoleixin1994  - we do at least have basic disk detection parallelized, see:
https://github.com/py4dstem/py4DSTEM/blob/dev/py4DSTEM/process/diskdetection/diskdetection_parallel.py

This is slightly out of date however - we're working on bringing it back into the main package.  All of the image-by-image processing steps can in theory be parallelized, and we're working on it!
