### ISSUE TITLE
For those under windows with scipy, blas and lapack problems....

### ISSUE THREAD

**Issue by AutoEM** [py4dstem/py4DSTEM#181]
I had several problems installing scipy==1.5.2, and the remedies out there seemed to be quite involved.
For those with similar issues, the following easy bypass method worked for me:

1. install py4dstem as stated in the readme section. For me this installed 0.11.5 as the first working version.
2. install scipy with conda:   conda install scipy==1.5.2
3. install py4dstem with pip:    pip install py4dstem==0.12.3 --no-dependencies

For me this worked....

**Comment by sezelt** [comment]
This should now be solved, since we removed any strict version dependencies
