### ISSUE TITLE
Minor suggestion: add boolean to diable the progress bar

### ISSUE THREAD

**Issue by zml941116** [py4dstem/py4DSTEM#187]
Hi, Thanks a lot for developing this package, it helps a lot for my research. Just a minor suggestion, it might be helpful to add a boolean to disable the progress bar, especially when the user is trying to iterate over the reciprocal space.

**Comment by sezelt** [comment]
Hi Menglin,
Thanks for the suggestion.
Is there a particular function that you're using iteratively that's leaving a lot of progressbars behind?

**Comment by zml941116** [comment]
Hi Sezelt,
Thanks for the swift response. I am using virtualimage as a function of inner and outer collection angles. Iterating over the entire reciprocal space leaves a lot of progressbars.
