### ISSUE TITLE
Elapsed time

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#19]
For times over an hour, the time rendering is wrong, i.e. 94 minutes is rendered as "1h 94m".

Should be 
`print("Analyzed {} diffraction patterns in {}h {}m {}s".format(len(Rx), int(t/3600),
                                                                   int((t%3600)/60), int(t%60)))` ?
i.e. add t%3600 to the minutes part

**Comment by bsavitzky** [comment]
Good catch, thanks! Added this edit to my current working branch.
