### ISSUE TITLE
Any example codes about file pre-processing?

### ISSUE THREAD

**Issue by w4m0330** [py4dstem/py4DSTEM#196]
I am new to py4dstem and would like to move my 4dstem data analysis workflow from DM to python. 
The documents is incomplete at the moment and the examples are all about analysis but not about file preprocessing (importing, center beam alignment, crop, distortion correction etc.)
I would like to test the workflow from the 4DSTEM datasets out of TFS Velos (.MRC file, should be no problem using HyperSpy library) and proceed with alignment, crop, distortion correction, background subtraction etc. I think this can be very useful for many Velox users (who have high-speed Ceta camera) and do nano-beam diffraction type of 4DSTEM.
Thanks!

PS. I'm willing to contribute if the workflow works and established.

**Comment by ercius** [comment]
`py4DSTEM` uses `ncempy` to read DM files. `ncempy` already reads Velox EMD files for TEM/STEM images and diffraction patterns ([see here](https://openncem.readthedocs.io/en/latest/ncempy.io.html#module-ncempy.io.emdVelox)). This includes multidimensional data.

4D-STEM data should not be hard to read using `ncempy`. It might already work without any modifications. Velox data could then be directly loaded in py4DSTEM like DM files. If I have a test data set I could make sure `ncempy` is compatible with your files first.

**Comment by w4m0330** [comment]
> 
> 
> `py4DSTEM` uses `ncempy` to read DM files. `ncempy` already reads Velox EMD files for TEM/STEM images and diffraction patterns ([see here](https://openncem.readthedocs.io/en/latest/ncempy.io.html#module-ncempy.io.emdVelox)). This includes multidimensional data.
> 
> 4D-STEM data should not be hard to read using `ncempy`. It might already work without any modifications. Velox data could then be directly loaded in py4DSTEM like DM files. If I have a test data set I could make sure `ncempy` is compatible with your files first.

The question in the first place might be a bit vague. I'm not referring I/O problems, but rather the first steps after reading a file. Consider NBED 4D datasets, these include:
- beam shift correction (important particular when scan large FoV)
- measure and correct elliptical distortions
- reshape from 3D stack to 4D dataset.

BTW, how can I share an example dataset?

**Comment by sezelt** [comment]
Hi @w4m0330 ,
There are two locations where we keep (mostly) up-to-date example notebooks. The first is in the `sample_code` directory within the main py4DSTEM repo. The second is in a separate repo under the py4dstem organization, called `py4DSTEM_tutorials`.

* For beam shift correction, the best place to look is the notebook at `py4DSTEM/sample_code/strainmap_crystalline/calibrate.ipynb`, particularly at the section titled "Find the Origin". This uses the `py4DSTEM.process.calibration.get_origin` function to fit the center locations of each diffraction pattern. 
* For elliptical distortions, that same notebook also has a section called `Elliptical Distortion Calibration` which walks through the process. 
* To reshape from a 3D stack to 4D, simply create a `DataCube` using the 3D dataset, like `dc = py4DSTEM.io.datastructure.DataCube(data=the_3D_data)` then call the `set_scan_shape()` method on the datacube: `dc.set_scan_shape(n_pixels_x,n_pixels_y)`

These notebooks do assume data with crystalline diffraction and no beamstop. We also have some notebooks (not yet published in the repo) that shows how to use the same functions for doing elliptical calibration with amorphous rings and doing centering with a beamstop.
