### ISSUE TITLE
Error in threshold_Braggpeaks()

### ISSUE THREAD

**Issue by pettesmt** [py4dstem/py4DSTEM#223]
https://github.com/py4dstem/py4DSTEM/blob/dev/py4DSTEM/process/diskdetection/diskdetection.py

There is a typo in minPeakSpacing in the definition which doesn't match the code leading to error when using this function:
minPeakSpacing, minPeakSpcing

<img width="838" alt="Screen Shot 2021-10-24 at 6 31 24 PM" src="https://user-images.githubusercontent.com/52774159/138619104-e07bc78e-251e-47d4-82b0-3880c38471d9.png">

**Comment by bsavitzky** [comment]
Fixed in PR#227
