### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by tschoonj** [py4dstem/py4DSTEM#23]
Hi,

Would it be possible to make a PyPI release for py4DSTEM? As I have been asked to install this package into our anaconda environment, I need to turn it into a conda-package first, which is easier when I have access to PyPI release...

Thanks!

**Comment by bsavitzky** [comment]
Hi Tom,

A PyPI release is definitely part of the plan in the future! The timeframe
is not immediate, however - my projection for when the package is ready for
this (mostly this means low level implementation details, i/o, metadata
handling are sufficiently robust and a 'finalized' form) is end of summer.
Hope this helps!

Ben

**Comment by bsavitzky** [comment]
Going through old issues - very sorry not to have addressed this earlier.  The package is available now on pypi, see installation instructions in the README.
