### ISSUE TITLE
Issues trying to run the GUI in newest version

### ISSUE THREAD

**Issue by Espendb** [py4dstem/py4DSTEM#32]
Hi I tried to run the gui (following the instructions on github) and I got the following error.

##########################
(py4D-STEM) dyn-49-127-96-107:py4D-STEM espen$ python runGUI.py
QWidget: Must construct a QApplication before a QWidget
Abort trap: 6
########################
Running on a mac and in a completely "clean" conda environment except for py4DSTEM.
Might just be me making some silly mistake. Anyway, thought other people might run into similar issues.
Thanks for developing this though!
/Espen

**Comment by HamishGBrown** [comment]
Hey Espen, how are things going at MCEM? Was there a month or so but I think our paths diverged.

I think this is the same problem I was having on my windows laptop, here's the fix:

In viewer.py the initialization function (__init__) for the class DataViewer on line 49 starts with:

```
        QtWidgets.QMainWindow.__init__(self)
        self.this_dir, self.this_filename = os.path.split(__file__)

        # Define this as the QApplication object
        self.qtapp = QtWidgets.QApplication.instance()
        if not self.qtapp:
            self.qtapp = QtWidgets.QApplication(argv)
```

If you flip the order:

```
        # Define this as the QApplication object
        self.qtapp = QtWidgets.QApplication.instance()
        if not self.qtapp:
            self.qtapp = QtWidgets.QApplication(argv)
           
        QtWidgets.QMainWindow.__init__(self)
        self.this_dir, self.this_filename = os.path.split(__file__)
```

then the viewer works on Windows. Hopefully this translates to Mac as well

**Comment by Espendb** [comment]
Hey Hamish,
Yeah I think I was in DK at that time!
Things are good. Weather is sh… but that’s Melbourne right?
I’m drowning in data and stuff to do before leaving for good in September.
How is the US treating you…
The stuff Colin showed in his presentation here looked super cool.
Are you involved I the py4DSTEM project also?
Would be great to get some functionality of masking data according to know lattice structures…. (Diffraction patterns basically)…
Thanks for the tip - art now works with hspy files. It crashes with the EMPAD raw data (not sure if it actually should be able to read this).

If it really wants to stand out against other programs (4D-STEM explorer by J. LeBeau, or hyperspyUI…) it would be great to have several interactive ROI’s /detectors at the same time (basically what I eluded to in the top part of this mail).

Anyway thank you for the quick response!

/Espen

**Comment by bsavitzky** [comment]
Hey Espen and Hamish,

This bug has now been fixed in the master branch.  Thanks for the fix, Hamish, and for bringing the problem to our attention, Espen!  

As you've noted, Espen, the kind of thing you're talking about re: masking off Bragg peaks is indeed presently in progress, though it'll likely be a little longer before that functionality is cleaned up, documented, and in the api.  But coming soon to a py4DSTEM near you!

Ben
