### ISSUE TITLE
Documentation not building

### ISSUE THREAD

**Issue by swelborn** [py4dstem/py4DSTEM#353]
Hello! The documentation is not building (I think it hasn't been built in a long time) and I am wondering if I can help fix the problem by creating a [readthedocs yaml](https://docs.readthedocs.io/en/stable/config-file/v2.html).

Reason seems to be python version is 3.7 when building and skl doesn't like it, see here: https://readthedocs.org/projects/py4dstem/builds/18198166/

I think there is a way to enable documentation building on PRs in your readthedocs settings, see here: https://docs.readthedocs.io/en/stable/pull-requests.html

That way I could see if my PR will build properly.

Let me know and I will try it out.

**Comment by alex-rakowski** [comment]
They're back up and running
