### ISSUE TITLE
Incorrect reading of K2 datacubes

### ISSUE THREAD

**Issue by sdlszst** [py4dstem/py4DSTEM#36]
Reading datacubes from extracted K2 .dm files gives data arrays which are shifted to sit in between two diffraction patterns - i.e. calling datacube.data4D[rx,ry,:,:] yields an image which contains half of the DP at rx,ry and half of the next diffaction pattern in the scan.  This issue appears both with and without load='dmmmap'.

Data is on the \ncemnas\NCEM_Internal\Shiteng\TEAM-I\2019-06-27_aSi_4DSTEM\aSi12.dm4

**Comment by sezelt** [comment]
@sdlszst Can you pull from the dev branch and try on your data again? We have switched to the latest version of the .dm reader, which fixed this problem for some of our datasets.
Also, make sure you `pip install ncempy` in the conda environment where py4DSTEM lives (instructions [here](https://github.com/py4dstem/py4DSTEM/blob/dev/README.md#installation)).

**Comment by bsavitzky** [comment]
@sdlszst @sezelt Shiteng and I got this working on his machine, so closing this issue!
