### ISSUE TITLE
Error in WPF plot

### ISSUE THREAD

**Issue by alex-rakowski** [py4dstem/py4DSTEM#413]
@cophus @sezelt not sure if this is supposed to be walrus operator or what the correct operator. If its meant to be walrus, then we need to bump the python requirement to '>=3.8' 

```
c.f. def fit_to_mean_CBED
im = ax.matshow(
            err_im := -(DP - self.meanCBED),
            cmap=CyRd,
            vmin=-np.abs(err_im).max() / 4,
            vmax=np.abs(err_im).max() / 4,
        )

```
https://github.com/py4dstem/py4DSTEM/blob/d76ff5753c70968f1bd909186ad5eb9d730eeb30/py4DSTEM/process/wholepatternfit/wpf.py#L188

**Comment by bsavitzky** [comment]
I don't think the walrus is not actually doing anything, as this is an internal variable to `matshow` and it doesn't look like it gets used again - if that's correct we can just remove it

**Comment by alex-rakowski** [comment]
I did a quick search, and this seems to the only walrus operator in the repo. Its use is quite nice here, but we could create it outside the `matshow`  I think.

**Comment by bsavitzky** [comment]
Oh I see, it's used in the subsequent args to the same `matshow` call.  I think I would just remove this for simplicity.  That said, requiring Python >= 3.8 should happen soon, irrespective of any walrii
