### ISSUE TITLE
Problem with ACOM

### ISSUE THREAD

**Issue by Psiche91** [py4dstem/py4DSTEM#440]
Hello,
Thank you very much for your developing this package.
I have a problem with the command `crystal.match_single_pattern`  and therefore with `crystal.match_orientations`.
I follow the step to step of the Tutorial 'ACOM of AuAgPd nanowires - disk detection'

When I run the command:

 ` xind, yind = 32,96  ` 
 ` orientation  = crystal.match_single_pattern(  ` 
  ` bragg_peaks.vectors[xind,yind],  ` 
  ` # plot_corr = True, ` 
 ` # plot_polar = False, ` 
    ` verbose = True) ` 

Occur this error: **AttributeError: 'Crystal' object has no attribute 'orientation_gamma**'
the exaclty problem is along line 839 : '**dphi = self.orientation_gamma[1] - self.orientation_gamma[0]'**

I make the Pixel calibration, imported the .cif file of the structure, i make all steps of the tutorial.

I don't aspect the perfect fitting, but this error is very strange to me.
And I haven't ideas to resolve.

Thanks a lot 
Psiche

**Comment by sezelt** [comment]
Did you create an orientation plan (by calling `crystal.orientation_plan`) before trying to run `crystal.match_single_pattern`? The orientation plan precomputes the library of diffraction patterns to compare your experimental patterns against, so it has to be performed first. Can you also let us know what version of py4DSTEM you are using (the output of `py4DSTEM.__version__`)

**Comment by Psiche91** [comment]
Hello @sezelt 
no, I didn't, where i can find this command ?
The version of py4DSTEM is 0.13.17

Thanks a lot for the quick replay

**Comment by Psiche91** [comment]
Good morning Sezelt,
Thank you very much for the quick reply.
I managed to do it
