### ISSUE TITLE
cupy error when running ptychography

### ISSUE THREAD

**Issue by dsmagiya** [py4dstem/py4DSTEM#457]
Hi I am getting this cupy error when running ptychography in the tutorial notebooks. Could it be a GPU allocation issue? Thanks for the help!

Performing 48 iterations using a potential object type, with the gradient-descent algorithm, with normalization_min: 1.
Reconstructing object and probe:   0%|                | 0/48 [00:00<?, ? iter/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[51], line 1
----> 1 ptycho_13nm = ptycho_13nm.reconstruct(
      2     reset=True,
      3     store_iterations=True,
      4     max_iter = 48,
      5     normalization_min=1,
      6     step_size=0.5,
      7 ).visualize(
      8     iterations_grid = 'auto'
      9 )

File ~/anaconda3/envs/py4dstem-aiml/lib/python3.9/site-packages/py4DSTEM/process/phase/iterative_singleslice_ptychography.py:1541, in SingleslicePtychographicReconstruction.reconstruct(self, max_iter, reconstruction_method, reconstruction_parameter, max_batch_size, seed_random, step_size, normalization_min, positions_step_size, pure_phase_object_iter, fix_com, fix_probe_iter, symmetrize_probe_iter, fix_probe_amplitude_iter, fix_probe_amplitude_relative_radius, fix_probe_amplitude_relative_width, fix_probe_fourier_amplitude_iter, fix_probe_fourier_amplitude_threshold, fix_positions_iter, constrain_position_distance, global_affine_transformation, gaussian_filter_sigma, gaussian_filter_iter, probe_gaussian_filter_sigma, probe_gaussian_filter_residual_aberrations_iter, probe_gaussian_filter_fix_amplitude, butterworth_filter_iter, q_lowpass, q_highpass, butterworth_order, object_positivity, shrinkage_rad, fix_potential_baseline, switch_object_iter, store_iterations, progress_bar, reset)
   1539 # constraints
   1540 self._positions_px = positions_px.copy()[unshuffled_indices]
-> 1541 self._object, self._probe, self._positions_px = self._constraints(
   1542     self._object,
   1543     self._probe,
   1544     self._positions_px,
   1545     fix_com=fix_com and a0 >= fix_probe_iter,
   1546     symmetrize_probe=a0 < symmetrize_probe_iter,
   1547     probe_gaussian_filter=a0
   1548     < probe_gaussian_filter_residual_aberrations_iter
   1549     and probe_gaussian_filter_sigma is not None,
   1550     probe_gaussian_filter_sigma=probe_gaussian_filter_sigma,
   1551     probe_gaussian_filter_fix_amplitude=probe_gaussian_filter_fix_amplitude,
   1552     fix_probe_amplitude=a0 < fix_probe_amplitude_iter
   1553     and a0 >= fix_probe_iter,
   1554     fix_probe_amplitude_relative_radius=fix_probe_amplitude_relative_radius,
   1555     fix_probe_amplitude_relative_width=fix_probe_amplitude_relative_width,
   1556     fix_probe_fourier_amplitude=a0 < fix_probe_fourier_amplitude_iter
   1557     and a0 >= fix_probe_iter,
   1558     fix_probe_fourier_amplitude_threshold=fix_probe_fourier_amplitude_threshold,
   1559     fix_positions=a0 < fix_positions_iter,
   1560     global_affine_transformation=global_affine_transformation,
   1561     gaussian_filter=a0 < gaussian_filter_iter
   1562     and gaussian_filter_sigma is not None,
   1563     gaussian_filter_sigma=gaussian_filter_sigma,
   1564     butterworth_filter=a0 < butterworth_filter_iter
   1565     and (q_lowpass is not None or q_highpass is not None),
   1566     q_lowpass=q_lowpass,
   1567     q_highpass=q_highpass,
   1568     butterworth_order=butterworth_order,
   1569     object_positivity=object_positivity,
   1570     shrinkage_rad=shrinkage_rad,
   1571     object_mask=self._object_fov_mask_inverse
   1572     if fix_potential_baseline and self._object_fov_mask_inverse.sum() > 0
   1573     else None,
   1574     pure_phase_object=a0 < pure_phase_object_iter
   1575     and self._object_type == "complex",
   1576 )
   1578 self.error_iterations.append(error.item())
   1579 if store_iterations:

File ~/anaconda3/envs/py4dstem-aiml/lib/python3.9/site-packages/py4DSTEM/process/phase/iterative_singleslice_ptychography.py:1083, in SingleslicePtychographicReconstruction._constraints(self, current_object, current_probe, current_positions, pure_phase_object, fix_com, symmetrize_probe, probe_gaussian_filter, probe_gaussian_filter_sigma, probe_gaussian_filter_fix_amplitude, fix_probe_amplitude, fix_probe_amplitude_relative_radius, fix_probe_amplitude_relative_width, fix_probe_fourier_amplitude, fix_probe_fourier_amplitude_threshold, fix_positions, global_affine_transformation, gaussian_filter, gaussian_filter_sigma, butterworth_filter, q_lowpass, q_highpass, butterworth_order, object_positivity, shrinkage_rad, object_mask)
   1075     current_object = self._object_butterworth_constraint(
   1076         current_object,
   1077         q_lowpass,
   1078         q_highpass,
   1079         butterworth_order,
   1080     )
   1082 if shrinkage_rad > 0.0 or object_mask is not None:
-> 1083     current_object = self._object_shrinkage_constraint(
   1084         current_object,
   1085         shrinkage_rad,
   1086         object_mask,
   1087     )
   1089 if self._object_type == "complex":
   1090     current_object = self._object_threshold_constraint(
   1091         current_object, pure_phase_object
   1092     )

File ~/anaconda3/envs/py4dstem-aiml/lib/python3.9/site-packages/py4DSTEM/process/phase/iterative_ptychographic_constraints.py:75, in PtychographicConstraints._object_shrinkage_constraint(self, current_object, shrinkage_rad, object_mask)
     73 else:
     74     if object_mask is not None:
---> 75         shrinkage_rad += current_object[..., object_mask].mean()
     77     current_object -= shrinkage_rad
     79 return current_object

File cupy/_core/core.pyx:1313, in cupy._core.core.ndarray.__getitem__()

File cupy/_core/_routines_indexing.pyx:41, in cupy._core._routines_indexing._ndarray_getitem()

File cupy/_core/_routines_indexing.pyx:739, in cupy._core._routines_indexing._getitem_mask_single()

File cupy/_core/_routines_indexing.pyx:694, in cupy._core._routines_indexing._prepare_mask_indexing_single()

IndexError: tuple index out of range

**Comment by gvarnavi** [comment]
Hey @dsmagiya,

This is a curious bug.. Is this is in the [multislice tutorial](https://github.com/py4dstem/py4DSTEM_tutorials/blob/main/notebooks/ptycho03_STO-multislice.ipynb)?

Which version are you on?  (and if 0.14.1, did you install through pypi/conda or is this a local dev install)?
Also, can you see what the output of `ptycho_13nm._object_fov_mask_inverse` is? This should be a boolean numpy array.

**Comment by dsmagiya** [comment]
Hi Georgios, thanks so much for the quick reply. I have 0.14.1 and installed using anaconda. The output of `ptycho_13nm._object_fov_mask_inverse` is

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ...,  True,  True,  True],
       ...,
       [False, False,  True, ..., False, False,  True],
       [False, False,  True, ..., False, False,  True],
       [False,  True,  True, ...,  True,  True,  True]])

**Comment by gvarnavi** [comment]
Hmm, that looks correct to me... 

What cupy version are you using?  
I wonder if it's related to this [issue re: boolean indexing](https://github.com/cupy/cupy/issues/4693#issuecomment-788950506) in cupy. Although it seems like v10+ cupy [added support for all indexing operations ](https://github.com/cupy/cupy/pull/6196) and I would be surprised if you're running anything earlier than that?

**Comment by dsmagiya** [comment]
Hi Georgios, that was indeed the issue! Somehow I had v9.1. Reinstalling cupy has fixed it. Thanks so much.

**Comment by gvarnavi** [comment]
Great, glad to hear this fixed it!

@bsavitzky @sezelt - Let's bump the minimum cupy version in the optional install to at-least 10.0.0?
See [release notes](https://github.com/cupy/cupy/releases/tag/v10.0.0) with fancy indexing highlighted as the first feature.
