### ISSUE TITLE
`emdfile` version mismatch

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#458]
It seems that in `emdfile` the `RootedNode` class was removed in `v0.0.9`, while it is still imported (and perhaps used?) in `py4DSTEM`. This seems to be causing the PR build tests to be failing for several open PRs (#456, #455, #441). Currently PyPI is at 0.0.9 and so `pip` installations of py4DSTEM are broken, but the conda-forge release is one version behind and is working for the moment. 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/__init__.py", line 17, in <module>
    from py4DSTEM.classes import (
  File "/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/classes/__init__.py", line 5, in <module>
    from py4DSTEM.classes.datacube import DataCube
  File "/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/classes/datacube.py", line 6, in <module>
    from emdfile import Array,RootedNode
ImportError: cannot import name 'RootedNode' from 'emdfile' (/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/emdfile/__init__.py)
Error: Process completed with exit code 1.
```

I am not sure how hard it would be to cut `RootedNode` out of py4DSTEM and do a hotfix release, versus reverting it in emdfile...

**Comment by bsavitzky** [comment]
Yup, should have synced this last emdfile version update yesterday with the associated changes in py4DSTEM.  Because I didn't we're getting failed builds in the flaker GH action.  PR 459 fixes this - once it's pulled in the other 3 active PRs should pull from dev and the issue should resolve
