### ISSUE TITLE
If/Else control produces identical print result

### ISSUE THREAD

**Issue by swelborn** [py4dstem/py4DSTEM#517]
I notice here that this if/else is identical:
https://github.com/py4dstem/py4DSTEM/blob/a2841c331f181957900356fa83fdb012bff42c87/py4DSTEM/process/phase/iterative_parallax.py#L906

**Comment by gvarnavi** [comment]
Good catch, fixed with commit c06ca46 in `phase_contast`.  
Will be merged in `main` before next release.
