### ISSUE TITLE
Input data formatting

### ISSUE THREAD

**Issue by crmayerVCU** [py4dstem/py4DSTEM#526]
I am working on some code to capture 4D stem datasets on a JEOL TEM without a fancy direct electron detector (using PyJEM control and the regular camera so its going to be comparatively slow) and wanted to ask some questions about the best way to structure it to work with py4DSTEM. Im hoping to make it as seamless as possible and am already using the IO commands included in py4DSTEM to make the .h5 files.

First for the intensity scaling when saving, is a particular bit rate/datatype used for the numerical data or is whatever the original numpy array was formatted as carried over? If its carried over from the numpy array is that flexible after the datacube is made or should I make sure to set that appropriately when the object is initialized? Also does py4DSTEM expect log or linear scaled diffraction patterns? Id like to log scale them since it seems like you could get away with lower bit images that way but I can keep them linear if it causes problems downstream in the analysis.  

Second since my acquisition rate is going to be slow, I am also going to be able to acquire line scans and user selected points in addition to full 4D datasets. I was planning to still save the patterns as 1xN datacubes, is that the best way to do it and is there anything I have to set up in the calibration metadata to not have this cause problems later?

**Comment by sezelt** [comment]
* Any numpy datatype can be used to make the DataCube, and that will be kept.
* Once the DataCube is made, you can change the array later to be a different datatype.
* py4DSTEM expects linear scaled patterns in all of it analyses. Log scaling the data and casting to a lower bit depth is a lossy process, so I would not recommend it. 
* There should be no problem with having a 1 x N x X x Y DataCube. If you are saving a single pattern, I would recommend instead saving it as a DiffractionSlice (though there is nothing stopping you from saving a 1 x 1 x X x Y DataCube)
