### ISSUE TITLE
Loading from existing arrays

### ISSUE THREAD

**Issue by Cheng-Zhao-MCEM** [py4dstem/py4DSTEM#529]
Just a simple importing question, in Jupyter Notebook, if I already have an array (dimension (13,13,128,128)) named 'results', how do I import/load this to py4DSTEM? Do I have to save it to a dat file first or there is a straightforward way to do it?

Thanks in advance.

**Comment by sezelt** [comment]
All you need is `dataset = py4DSTEM.DataCube(data = results)`
