### ISSUE TITLE
File format spec

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#54]
Ben, is there documentation of what is required to have a v0.5 py4DSTEM file? IDES has made a program for converting Relativity data to emd/hdf5 but it follows Colin's v0.2 spec and py4DSTEM won't read them. Is there something we can point them to that indicates the latest specification?

**Comment by bsavitzky** [comment]
Hey Steven - Luis made the latest fileformat changes from v0.4 to v0.5 for PRISM compatibility, so I've asked him to update the file/io/fileformat.txt file accordingly.  Once that's updated this should be the place to go for this information.

**Comment by bsavitzky** [comment]
Ok, the file format specifications are now updated in file/io/fileformat.txt.  All the relevant info should be there, but let me know if anything you and/or Relativity peeps need is missing.  Note that we've also now versioned to v0.6!
