### ISSUE TITLE
Error importing '.raw' files

### ISSUE THREAD

**Issue by Cheng-Zhao-MCEM** [py4dstem/py4DSTEM#546]
Dear brilliant developers,

Sorry this might be another basic question, but I had a simulated 4dstem file in '.raw' format (80,80 real and 1024, 1024 diffraction). When I'm importing this to py4dstem:

> filepath = "./15mrad/oversampledRealSpace_15mrad_4DSTEM_191.055_1024x1024x84x84.raw"
> 
> datacube = py4DSTEM.import_file(
>     filepath,
>     # EMPAD_shape = (84, 84, 1024, 1024)
> )

With or without the 'EMPAD_shape' command, it gives me a Value Error: cannot reshape array of size 7398752256 into shape (1,1,130,128). 

do you have any idea what the issue is and how to possibly fix it?

Thanks in advance!
Cheng

**Comment by sezelt** [comment]
Hi Cheng, the py4DSTEM reader can only natively open `.raw` files produced by an EMPAD at the moment. What detector did you use to acquire the data? We will need to know the layout and the datatype of the file to show you how to read it.

**Comment by Cheng-Zhao-MCEM** [comment]
Thanks for the reply, unfortunately this is not an acquired data but simulated. I used multislice code by Hamish. Is there any way to read this type of data?

**Comment by alex-rakowski** [comment]
@Cheng-Zhao-MCEM Are you still having issues with this?

**Comment by Cheng-Zhao-MCEM** [comment]
hey Alex,

Already had it sorted out! Thanks!

Cheers,
Cheng
