### ISSUE TITLE
cannot import py4DSTEM module (`np.bool` deprecation?)

### ISSUE THREAD

**Issue by yongsooyang** [py4dstem/py4DSTEM#582]
**Describe the bug**
py4DSTEM module not loading (gpu)

**To Reproduce**
Steps to reproduce the behavior, please be as general as possible, and ideally recreate a minimal reproducible example:

**Expected behavior**
successfully imported py4DSTEM

**py4DSTEM version** 
I cannot load the py4DSTEM module, so cannot check. I conda installed py4DSTEM (with GPU) on 11/25/2023.

**Python version**
Python 3.9.18

**Operating system** 
Windows

**GPU**
If GPU related please provide:
- CUDA driver - 545.84   CUDA 12.3
- Cupy Version - It can be accessed by `cupy.__version__`
- I cannot load the Cupy  module due to the same error, so cannot check. I conda installed Cupy on 11/25/2023.

![screenshot](https://github.com/py4dstem/py4DSTEM/assets/24594416/767cd96a-bd5e-46c3-9039-fa02534769ae)

**Comment by yongsooyang** [comment]
This problem was resolved by downgrading numpy versiona as follows:

conda install -c conda-forge cupy numpy==1.23.1

**Comment by gvarnavi** [comment]
Thanks for reporting (and self-debugging) @yongsooyang! Closing this based on discussion in #583.
