### ISSUE TITLE
Suggestions for 2D Materials with Large Unit Cell 

### ISSUE THREAD

**Issue by amalyacox** [py4dstem/py4DSTEM#613]
Hello, 
I'm trying to simulate dynamical diffraction for twisted structures of 2D materials, like twisted bilayer graphene. The unit cell of these systems requires many ~ 3200 - 43000 atoms. With 3200 atoms, Crystal.calculate_structure_factors needs an array of ~200GB. Any suggestions for working with these systems? 
Thanks

**Comment by sezelt** [comment]
The Bloch wave method in general is best suited to small unit cells, and the memory usage increases as the number of beams squared and the computation time as the number of beams cubed. For a Moiré system it may be possible to choose the beams that get included in the calculation in a smart way so as to avoid having an untenably large calculation but we don't have that built in at the moment. Multislice will probably work better for this application: abTEM has some useful utilities for constructing simulation cells with multiple rotated lattices [here](https://abtem.readthedocs.io/en/latest/user_guide/tutorials/advanced_atomic_models.html)

**Comment by amalyacox** [comment]
thank you!!
