### ISSUE TITLE
Realslice object has no attribute R_N

### ISSUE THREAD

**Issue by reiszadeh** [py4dstem/py4DSTEM#64]
Hi. I am a new user. when I want to load my output file in 4DSTEM in linux with  py4DSTEM GUI ,I encounter with this error:

Loading file /home/4dstem/barium.h5
/home/sevin/software/4dstem/barium.h5 is a py4DSTEM file, v0.5. Reading...
(224, 128, 8)
Traceback (most recent call last):
File "/home/py4DSTEM/py4DSTEM/gui/viewer.py", line 317, in update_scan_shape_Nx
self.settings.R_Ny.update_value(int(self.datacube.R_N/R_Nx))
AttributeError: 'RealSlice' object has no attribute 'R_N'
Aborted (core dumped)

would you please help me. by the way, Is there any manual of this code.

my parameters are:
--alpha-max:32
--batch-size-cpu:1
--probe-step-x:0.20
--probe-step-y:0.20
--cell-dimension:22.347900 12.202100 7.695500
--tile-uc:1 1 1
--probe-defocus:0
-C3:0
-C5:0
--probe-semiangle:30
--detector-angle-step:2
--probe-xtilt:0
--probe-ytilt:0
--scan-window-x:0 0.99999
--scan-window-y:0 0.99999
--random-seed:44399
--thermal-effects:1
--occupancy:1
--save-potential-slices:1
--save-real-space-coords:1
--nyquist-sampling:1
--also-do-cpu-work:1
--batch-size-gpu:1
--num-gpus:4
--num-streams:8

**Comment by sezelt** [comment]
It seems that the GUI is reading the wrong dataobject from the h5 file. Can you run
```python
import py4DSTEM
fb = py4DSTEM.file.io.FileBrowser('/home/sevin/software/4dstem/barium.h5')
fb.show_dataobjects()
fb.close()
```
and attach the output? I'd like to see the structure of the h5 file that's causing the error

**Comment by reiszadeh** [comment]
I have run your commands and the result is:
Index                  Name                        Type        
   0    ppotential                          RealSlice           
   1    virtual_detector_depth0000          RealSlice           
I have got 3D images, please let me know how can I handle it and visualize the picture with py4DSTEM

**Comment by sezelt** [comment]
Hi @reiszadeh, currently the GUI data browser currently supports only 4D data. You'll have to use numpy and matplotlib to generate virtual images from Prismatic outputs. To load the 3D data as a numpy array you can use (in a Jupyter notebook)
```python
import numpy as np
import matplotlib.pyplot as plt
fb = py4DSTEM.file.io.FileBrowser('/home/sevin/software/4dstem/barium.h5')
fb.show_dataobjects()
sim = fb.get_dataobject(1) # the argument corresponds to the Index displayed by the above command
fb.close()
```
The data itself should be located in `sim.data`, as a numpy ndarray, so you could make a virtual brightfield image with something like 
```python
fig, ax = plt.subplots()
ax.matshow(np.sum(sim.data[:,:,0:10],axis=2))
plt.show()
```

**Comment by bsavitzky** [comment]
Closing this as an old issue, and which the comments above seem to have addressed.
