### ISSUE TITLE
"Solving environment: failed with initial frozen solve. Retrying with flexible solve." During installation

### ISSUE THREAD

**Issue by Cheng-Zhao-MCEM** [py4dstem/py4DSTEM#649]
Might be a basic question but I am encountering this in both windows and linux (Ubuntu22.04.3LTS):
During my installation according to https://py4dstem.readthedocs.io/en/latest/installation.html#recommended-installation, when I do 
` conda install -c conda-forge py4dstem`, 
I always seem to fail (both win and linux) by the following error message:
`Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ Killed`
Just writing here to see if anyone knows a fix to this? My current conda version is 23.5.2 for Ubuntu and 22.9.0 for Windows.

Thanks in advance!

**Comment by sezelt** [comment]
What version of Python did you specify when creating the environment? The instructions you linked are out of date (they have been fixed in the development version but not on the website yet), and specifying 3.9 will likely not work anymore. Can you try instead specifying Python 3.12 when creating the environment?

**Comment by sezelt** [comment]
By the way, you can pass that argument to the top level reader:
`datacube = py4DSTEM.import_file("/path/to/data.raw", EMPAD_shape=(256,16))`
