### ISSUE TITLE
dp_mask not on device

### ISSUE THREAD

**Issue by ARSadri** [py4dstem/py4DSTEM#651]
thanks for your useful fast software

**dp_mask not on device**

When passing dp_mask to reconstruct in multislice ptychography, i sent a 2d numpy, Debug shows that in the following file/line dp_mask is not on device:

py4DSTEM/py4DSTEM/process/phase/phase_base_class.py : line 689, 
`
     intensities_mask = intensities * dp_mask
`

**My workaround::**
```
    intensities_mask = intensities * copy_to_device(dp_mask, device)
```

**py4DSTEM version** 
0.14.8

Best regards
Alireza

**Comment by gvarnavi** [comment]
Thanks for reporting the issue @ARSadri.  
Indeed, this was a bug that has been fixed a while ago (circa version 0.14.9).

For your reference, this the [updated line](https://github.com/py4dstem/py4DSTEM/blob/dev/py4DSTEM/process/phase/phase_base_class.py#L676) in the current version.

Can you perhaps update to the newest version (0.14.14)? Note the API has changed a bit, as discussed at the top of the [README](https://github.com/py4dstem/py4DSTEM/blob/dev/README.md) file. Hoping to find time update the tutorials very soon..
