### ISSUE TITLE
Show scalebar parameters don't take effect if ar.calibration is not None

### ISSUE THREAD

**Issue by edwinsupple** [py4dstem/py4DSTEM#672]
**Describe the bug**
when using `py4DSTEM.visualize.show`, a dictionary passed to `scalebar` is ignored if the plotted image has a calibration parameter (e.g. virtual bright field images)

**To Reproduce**
```
import py4DSTEM
from py4DSTEM.visualize import show
import numpy as np

datacube = py4DSTEM.DataCube(np.random.rand(10,10,128,128))

datacube.calibration.set_Q_pixel_units('mrad') # arbitrary values to fill out calibration
datacube.calibration.set_Q_pixel_size(0.03)
datacube.calibration.set_R_pixel_units('nm')
datacube.calibration.set_R_pixel_size(3)

bf1 = datacube.get_virtual_image(mode='circle', geometry = ((64,64), 30))

show(bf1) # displays the default scalebar
show(bf1, scalebar={'position':'bl', 'color':'k'})  # scalebar still in same position and color as default

```
**Expected behavior**
Would expect the default scalebar parameters to take effect, except for any that are passed to the function in the scalebar dictionary.

**py4DSTEM version** 
0.14.15

**Python version**
3.10.4
**Operating system** 
Windows 

**Screenshots**
If applicable, could you add screenshots to help explain your problem?
current functionality, showing parameter passed to `scalebar` as axis title:
![scalebar_functionality-old](https://github.com/user-attachments/assets/b64ea1f7-c2bd-403b-9991-b736ab48bcd4)

expected behavior:
![scalebar_functionality-new](https://github.com/user-attachments/assets/11b278b2-385d-4ffd-a310-dfb02d14efba)

**Comment by bsavitzky** [comment]
Thank you Edwin!
