### ISSUE TITLE
Availability of sample data mentioned in notebooks?

### ISSUE THREAD

**Issue by nikhild1836** [py4dstem/py4DSTEM#71]
I have installed py4DSTEM in windows and the installation seems to have completed fine. I tried using the provided notebooks but it seems that the sample data files mentioned (Sample_LFP_datacube.h5) is not included.

Is it possible to have access to the sample data files? Thanks.

**Comment by bsavitzky** [comment]
Hi Nikhil - thanks for the note about sample data.  We can absolutely
provide some sample datasets.  I need to check in about which datasets will
be best to share, so it may take a day or two - I'll message again when
something is available.

**Comment by bsavitzky** [comment]
Closing out this issue - at present all sample code for demo notebooks lives here: https://drive.google.com/drive/folders/1GmxF1ltY7hBU4d5ZK8INXjaRW5Etnw_4
