### ISSUE TITLE
cupy dependency breaks support for machines without GPU

### ISSUE THREAD

**Issue by sezelt** [py4dstem/py4DSTEM#76]
Cannot import py4DSTEM because the SSB code imports `cupy`, which _cannot_ be installed on machines without an NVIDIA GPU.

Switch to SigPy?

```python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3fd97a04de54> in <module>
      8 from py4DSTEM.file.io import read, h5read
      9 from py4DSTEM.process.utils import Param
---> 10 from py4DSTEM.process.ptychography import weak_phase_reconstruction
     11 import h5py

~/git-repos/py4DSTEM/py4DSTEM/process/ptychography/__init__.py in <module>
----> 1 from .ssb import *
      2 from .wdd import *

~/git-repos/py4DSTEM/py4DSTEM/process/ptychography/ssb.py in <module>
      1 import time
      2 from py4DSTEM.file.datastructure import DataCube
----> 3 import cupy as cp
      4 import torch as th
      5 import numpy as np

ModuleNotFoundError: No module named 'cupy'
```

**Comment by bsavitzky** [comment]
Hmm, this is a problem.  Thanks Steven.  @PhilippPelz - can we import cupy (and perhaps also torch) conditionally if appropriate hardware is available?

**Comment by PhilippPelz** [comment]
yep, need to figure out how to check for that without actually using those libraries.

**Comment by PhilippPelz** [comment]
wait, but pytorch can be installed without GPU, so I can check torch.cuda.is_available() and optionally include cupy.

is that ok with you, @bsavitzky ?

**Comment by bsavitzky** [comment]
Sounds good to me.
