### ISSUE TITLE
Using non-standard characters

### ISSUE THREAD

**Issue by tcpekin** [py4dstem/py4DSTEM#86]
Hello all, hope all is going well. I have been looking into actually contributing something (finally) with regards to amorphous pattern analysis, and have been looking through the current dev code as a guide. However, I saw that the ptychography module has a lot of non-standard characters used, like Γ and such. I kind of am of the opinion that these are hard to work with/edit unless you have specific keybindings and such. What is the policy on these non ascii/english characters being used?

**Comment by bsavitzky** [comment]
Hey Tom - in general, my strong preference is to only use standard
characters.  Sooooome of us (*cough philipp(!) cough*) have used
non-standard characters, as you noted - these should only be present in the
ptychography-related code.  It may be worth changing these at some point in
the future, but for now it's not high enough priority for me to mess with,
as that code is working at the moment.  Anyway, yeah, preference for
standard characters only, for the reason you've said!

**Comment by sezelt** [comment]
On the one hand, I like the improved readability from using greek letters, it makes things look more like the equations they represent.

However, we all know that single-letter variable names (`x`, `i`, `a`) are discouraged. Seemingly the use of variable names like `Γ` or `λ` violates this prohibition, and so they should be discouraged on that basis in favor of more descriptive names... 

But this raises a philosophical question: does a variable name like `gamma` or `lambda` count as a "single-letter" name, and thus something to be avoided on the same basis?

I think I shall conduct a Twitter poll to gauge the sentiment of the community... I'll report back here with the result.

**Comment by sezelt** [comment]
The votes are in, and among the 23 Twitter followers who responded the preferred variable name for electron wavelength is:
* `lambda` : 34.8%
* `λ` : 39.1%
* `electron_wavelength` : 26.1%

😛

**Comment by tcpekin** [comment]
In the spirit of trying to close my issues, I would suggest `electron_wavelength` or just `wavelength`, as everyone has tab complete and then there is no (or less) ambiguity. But if that is not what people want, we can close this issue.

**Comment by bsavitzky** [comment]
I'm finally going through and closing old issues.  I think we should stick with ascii in source code only!  I believe this is resolved but if it's still an issue we can re-open this later.  With apologies to Steve's 9 twitter followers in 2019 who wanted us to use λ

**Comment by sezelt** [comment]
undemocratic!

**Comment by bsavitzky** [comment]
;_;
