### ISSUE TITLE
GUI will not open - AttributeError: 'DataCube' object has no attribute 'data'

### ISSUE THREAD

**Issue by bdalevin** [py4dstem/py4DSTEM#89]
I've just installed py4dstem (on a Windows 10 machine), but I'm unable to open the GUI. I get the following error message after executing the command "py4dstem" in the Anaconda Prompt (see image attached):
![py4dstem error](https://user-images.githubusercontent.com/12704237/71833509-4cb7c500-306a-11ea-8686-2cc1e630d251.PNG)

If anyone knows how to fix this issue, that would be great!

**Comment by bdalevin** [comment]
The issue seems to be due to incompatibility between my python environment and py4dstem. 
I have found a solution, which I will detail below in case anyone else has a similar issue:

Instead of installing py4dstem in your main python environment, you can create a separate python environment for py4dstem before you install.

In the Anaconda Prompt, you can do this by typing: 
`conda create -n py4dtem python=3.7`. 

Then activate the new py4dstem environment by typing:
`conda activate py4dstem`

Now you need to install all of the prerequisite packages (hyperspy, h5py, etc) in the py4dstem environment, even if you have already installed them in your main python environment. 
After installing all prerequisites, you should be able to install and run py4dstem. Just remember that every time you want to run py4dstem, you will need to switch to your py4dstem environment.

**Comment by bsavitzky** [comment]
Barnaby you are a hero.  Thanks for posting both question and answer.

Ben

**Comment by bdalevin** [comment]
No problem Ben. Happy to help!
