### ISSUE TITLE
"pyqt5" not available in current channel.

### ISSUE THREAD

**Issue by Quantumstud** [py4dstem/py4DSTEM#96]
While executing "conda install pyqt5", there is an error which states that the package is not available in from the current channel. I think the current command should be "conda install -c dsdale24 pyqt5".

**Comment by matkraj** [comment]
on ubuntu pip install pyqt5 worked

**Comment by bsavitzky** [comment]
Sorry to only be getting to this now (!) - install is now handled through the setup file, all through the single pip install py4DSTEM command, so this should no longer be a problem.
